title: Handbook Data Science 2025
author: Руслан Назаров
execute:
  execute_notebooks: off
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

    - html_image
html:
  extra_css:
    - _static/custom.css
  google_analytics_id: "G-PLQBBT7CFS"
    
# Настройки автора и копирайта
author: "Назаров Руслан"
copyright: "2026"  # Или "2022–2026", если проект длительный

metadata:
  description: "История ИИ и его базовые концепции через призму диалектического подхода."
  keywords: "Искусственный интеллект, диалектика, Data Science, Руслан Назаров"
  image_path: "_static/logo.png" # Путь к обложке книги


