title: "О книге"
author: "Назаров Руслан"
copyright: "2026"

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - html_image

html:
  home_page_in_toc: true       # Включает подразделы index.md в меню
  logo: "logo.png"
  favicon: "logo.png"
  google_analytics_id: "G-PLQBBT7CFS"
  extra_css:
    - _static/custom.css
  navbar_brand_box_2:
    logo_only: false           # ВАЖНО: false, чтобы текст "О книге" появился

metadata:
  description: "История ИИ и его базовые концепции через призму диалектического подхода."
  keywords: "Искусственный интеллект, диалектика, Data Science, Руслан Назаров"
  image_path: "logo.png"

sphinx:
  config:
    html_theme_options:
      logo_only: false         # ВАЖНО: здесь тоже должно быть false
